# Generated by Django 3.2.5 on 2021-07-28 02:21

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django.utils.timezone
import post_office.fields
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='created',
        ),
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Optional, separate multiple addresses with a comma.', verbose_name='Email Bcc'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Optional, separate multiple addresses with a comma.', verbose_name='Email Cc'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(default=settings.EMAIL_ADMIN, help_text='Must have permission to send through the default server!', max_length=254, validators=[post_office.validators.validate_email_with_name], verbose_name='Email From'),
        ),
        migrations.AlterField(
            model_name='email',
            name='html_message',
            field=models.TextField(blank=True, help_text='Leave this blank if sending content by a template!', verbose_name='HTML Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(blank=True, help_text='Leave this blank if sending content by a template!', verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled sending time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, help_text='Leave this blank if sending content by a template!', max_length=989, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, help_text='If selected, will replace subject, plain-text content, and html content with content from the chosen template.', null=True, on_delete=django.db.models.deletion.CASCADE, to='post_office.emailtemplate', verbose_name='Email template'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Optional (if no group of recipients selected), separate addresses with a comma.', verbose_name='Email To'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(blank=True, default='\n\nClick the following link to unsubscribe from future emails: \nhttps://{{ unsubscribe }}', help_text='Plain text message for users who have HTML email disabled.', validators=[post_office.validators.validate_template_syntax], verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='description',
            field=models.CharField(blank=True, help_text='Description of this template.', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(blank=True, default='<br /><br /><p style="text-align:center;font-size:small;">Click <a href="https://{{ unsubscribe }}">here</a> to unsubscribe from future emails.</p>', help_text='Email HTML body. Context variables available for personalisation, ex: {{ first_name }} {{ last_name }} returns Joe Smith', validators=[post_office.validators.validate_template_syntax], verbose_name='HTML Content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text="ex: 'welcome_email'", max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, help_text='The email subject.', max_length=255, validators=[post_office.validators.validate_template_syntax], verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The scheduled sending time', null=True, verbose_name='Scheduled Time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, help_text='Leave this blank if sending content by a template!', max_length=999, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_office.emailtemplate', verbose_name='Email template'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this template.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text="e.g: 'welcome_email'", max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='email',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional, send email to all members of a group.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Send to group'),
        ),
        migrations.AlterField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional, use a pre-made template rather than typing the message content in this form.', null=True, on_delete=django.db.models.deletion.CASCADE, to='post_office.emailtemplate', verbose_name='Email template'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Optional if no group selected, separate addresses with a comma.', verbose_name='Email To'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(default=settings.EMAIL_ADMIN, help_text='Must have permission to send through the default server!', max_length=254, validators=[post_office.validators.validate_email_with_name], verbose_name='Email From'),
        ),
        migrations.AlterField(
            model_name='email',
            name='html_message',
            field=models.TextField(blank=True, help_text='Optional, no context variables, group sending, or unsubscribe link, leave blank if sending content by a template!', verbose_name='HTML Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(blank=True, help_text='Optional, no context variables, group sending, or unsubscribe link, leave blank if sending content by a template!', verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, help_text='Optional, no context variables, group sending, or unsubscribe link, leave blank if sending content by a template!', max_length=999, verbose_name='Subject'),
        ),
    ]
